language: python

python:
  - "3.3"

cache:
  directories:
    - venv

addons:
  postgresql: "9.3"

# command to install dependencies
install:
  - "virtualenv --python=python3.3 venv"
  - ". venv/bin/activate"
  - "pip install pytest"
  - "pip install -r requirements.txt"

env:
  - BAUBLE_DB_URL="postgresql://localhost/bauble"

before_script:
  # disable ssl mode on postgresql
  - sudo sed -i -e 's/ssl = true/#ssl = true/' /etc/postgresql/9.1/main/postgresql.conf
  - sudo service postgresql restart
  - echo "BAUBLE_ENV=travis" >> ~/.bauble.api
  - sudo adduser -disabled-password --gecos "" bauble
  - psql -c "create database bauble encoding 'utf8';" -U postgres
  - PYTHONPATH=. bin/initdb.py

# command to run tests
script: ./bake test
