#!/usr/bin/env python

import os
import sys
import subprocess

import yaml

try:
    import baker
except Exception as e:
    # TODO install baker and rerun
    print("baker not installed. pip install 'baker>=1.3,<2.0a0'")
    raise


os.environ['PYTHONPATH'] = os.getcwd()
#BAUBLE_DB_URL="postgresql://test:test@localhost/bauble" BAUBLE_ENV="development"

def load_env(name):
    environ = yaml.load(open("config.yaml"))
    os.environ.update(environ[name])


def shell(cmd, stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr):
    """
    Run a shell command.
    """
    try:
        return subprocess.check_call(cmd, stdin=stdin, stdout=stdout, stderr=stderr, shell=True)
    except subprocess.CalledProcessError as exc:
        print("** Error running command: {}".format(cmd))
        print(exc)
        sys.exit(exc.returncode)


@baker.command
def test(*args):
    """
    Deploy to the production environment.
    """
    load_env('test')
    pytest_args = ['py.test', 'test/spec'] if len(args) is 0 else ['py.test'] + list(args)
    shell(" ".join(pytest_args))


@baker.command
def virtualenv():
    # TODO: create the virtualenv and install the dependencies
    pass


@baker.command
def deploy():
    """
    Deploy to the production environment.
    """
    # TODO: copy to server and restart server
    pass


@baker.command
def clean():
    rm = lambda pattern: shell("find . -name {0} -type file | xargs -I {{}} rm -fr {{}}".format(pattern))
    rm("\*~")
    rm("\*.pyc")
    rm("__pycache__")


@baker.command(default=True)
def server(environment="local"):
    """
    Start the server
    """
    load_env(environment)


baker.run()
