#!/usr/bin/env python3

import os
import subprocess

import bauble

try:
    import baker
except Exception as e:
    # TODO install baker and rerun
    print("baker not installed. pip install 'baker>=1.3,<2.0a0'")
    raise


def run(args):
    os.environ['PYTHONPATH'] = os.getcwd()
    process = subprocess.Popen(args, env=os.environ)
    process.wait()


@baker.command
def test(*pytest_args):
    """
    Deploy to the production environment.
    """
    args = ["test/spec"] if len(pytest_args) is 0 else pytest_args
    run(['py.test'] + list(pytest_args))


@baker.command
def deploy():
    """
    Deploy to the production environment.
    """
    # TODO: copy to server and restart server
    pass


@baker.command
def server():
    """
    Start the server
    """
    if os.environ.get('BAUBLE_ENV') == ("development")  or \
       (len(sys.argv) > 1 and sys.argv[1].lower().startswith("dev")):
        host = '0.0.0.0'
        port = 9090
    else:
        host='api.bauble.io'
        port=80

    debug=False

    import bauble.server as server
    application = server.init()
    application.run(host=host, port=port, reloader=True, debug=debug)


baker.run()
